Do not always chomp output
ruby-git/ruby-git pull request #368
Opened 2018-06-04 08:42 UTC by smortex

This bunch of commits does some refactoring and adds a way to optionally disable chomping the output of commands.

This fixes #347 in respect to the `#show` method.  Other methods may need similar adjustment.

2020-11-21 17:58 UTC, jcouball requested changes
Looks like this PR is behind master.  If you are willing to get it caught up, I’ll take another look and if everything works, merge it.

2020-11-21 17:58 UTC, jcouball commented on lib/git/lib.rb
> +      command_opts = default_command_opts.merge(command_opts)
I think this is redundant because of line 953.

2020-11-24 04:51 UTC, smortex commented
@jcouball I rebased these changes on top of master.

2020-11-24 17:58 UTC, jcouball approved these changes
I prefer the keyword args for `chdir` and `chomp`.

Since it is a wide ranging change, I do have a concern that it will invalidate every open PR.  They will likely have to rebase.

2020-11-24 18:04 UTC, merged